export const currentFileVersion = 1;

export const brickToName = {
    "assembly:/_pro/scenes/missions/thefacility/outfits_prologue.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/paris/_scene_fashionshowhit_01.entity": "Paris",
    "assembly:/_pro/scenes/missions/paris/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/paris/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/coastaltown/_scene_octopus.entity": "Sapienza - World of Tomorrow",
    "assembly:/_pro/scenes/missions/coastaltown/tod_wot_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/coastaltown/_scene_mission_mamba.entity": "Sapienza - Landslide",
    "assembly:/_pro/scenes/missions/coastaltown/tod_day_landslide.brick": "Summer Day (2016)",
    "assembly:/_pro/scenes/missions/marrakesh/_scene_spider.entity": "Marrakesh - A Gilded Cage",
    "assembly:/_pro/scenes/missions/marrakesh/gilded_tod_summer_night_clear.brick": "Night",
    "assembly:/_pro/scenes/missions/marrakesh/lighting_dusk.brick": "Dusk",
    "assembly:/_pro/scenes/missions/marrakesh/_scene_python.entity": "Marrakesh - A House Built On Sand",
    "assembly:/_pro/scenes/missions/marrakesh/tod_ahbos_day.brick": "Midday",
    "assembly:/_pro/scenes/missions/bangkok/_scene_tiger.entity": "Bangkok - Club 27",
    "assembly:/_pro/scenes/missions/bangkok/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/bangkok/tod_zika_night.brick": "Night",
    "assembly:/_pro/scenes/missions/colorado_2/_scene_mission_bull.entity": "Colorado",
    "assembly:/_pro/scenes/missions/colorado_2/lighting_night.brick": "Night",
    "assembly:/_pro/scenes/missions/colorado_2/lighting_day.brick": "Midday",
    "assembly:/_pro/scenes/missions/hokkaido/_scene_mission_snowcrane.entity": "Hokkaido - Situs Inversus",
    "assembly:/_pro/scenes/missions/hokkaido/tod_flu.brick": "Midday",
    "assembly:/_pro/scenes/missions/hokkaido/tod_bluenight.brick": "Blue Night",
    "assembly:/_pro/scenes/missions/sheep/scene_sheep.entity": "Hawke's Bay",
    "assembly:/_pro/scenes/missions/sheep/tod_twilight.brick": "Dawn",
    "assembly:/_pro/scenes/missions/sheep/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/sheep/tod_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/miami/scene_flamingo.entity": "Miami",
    "assembly:/_pro/scenes/missions/miami/tod_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/miami/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/colombia/scene_hippo.entity": "Santa Fortuna",
    "assembly:/_pro/scenes/missions/colombia/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/mumbai/scene_mongoose.entity": "Mumbai",
    "assembly:/_pro/scenes/missions/mumbai/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/mumbai/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/skunk/scene_skunk.entity": "Whittleton Creek",
    "assembly:/_pro/scenes/missions/skunk/tod_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/skunk/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/theark/scene_magpie.entity": "Isle of Sgail",
    "assembly:/_pro/scenes/missions/theark/tod_midday.brick": "Daytime",
    "assembly:/_pro/scenes/missions/theark/tod_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/salty/mission_seagull/scene_seagull.entity": "Hantu Port (Sniper Assassin)",
    "assembly:/_pro/scenes/missions/salty/mission_seagull/tod_rainy_night.brick": "Rainy Night",
    "assembly:/_pro/scenes/missions/greedy/mission_raccoon/scene_raccoon_basic.entity": "New York",
    "assembly:/_pro/scenes/missions/greedy/mission_raccoon/raccoon_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/opulent/mission_stingray/scene_stingray_basic.entity": "Haven Island",
    "assembly:/_pro/scenes/missions/opulent/mission_stingray/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/golden/mission_gecko/scene_gecko_basic.entity": "Dubai",
    "assembly:/_pro/scenes/missions/golden/mission_gecko/midday_gecko.brick": "Midday",
    "assembly:/_pro/scenes/missions/ancestral/scene_bulldog.entity": "Dartmoor - Death In The Family",
    "assembly:/_pro/scenes/missions/ancestral/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/ancestral/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/edgy/mission_fox/scene_fox_basic.entity": "Berlin",
    "assembly:/_pro/scenes/missions/edgy/mission_fox/variant_easter.brick": "Easter Event",
    "assembly:/_pro/scenes/missions/edgy/mission_fox/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/edgy/mission_fox/tod_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/wet/scene_rat_basic.entity": "Chongqing",
    "assembly:/_pro/scenes/missions/wet/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/wet/tod_cloudy.brick": "Cloudy Day",
    "assembly:/_pro/scenes/missions/elegant/scene_llama.entity": "Mendoza",
    "assembly:/_pro/scenes/missions/elegant/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/trapped/scene_wolverine.entity": "Romania",
    "assembly:/_pro/scenes/missions/trapped/tod_day.brick": "Midday",
    "assembly:/_pro/scenes/missions/rocky/scene_dugong.entity": "Ambrose Island",
    "assembly:/_pro/scenes/missions/rocky/tod_midday.brick": "Midday",
    "assembly:/_pro/scenes/missions/rocky/tod_sunset.brick": "Sunset"
  };

export const brickToVersion = {

};

export const brickToImage = {
};

export const displayOrder = [
    "assembly:/_pro/scenes/missions/paris/_scene_fashionshowhit_01.entity",
    "assembly:/_pro/scenes/missions/coastaltown/_scene_octopus.entity",
    "assembly:/_pro/scenes/missions/coastaltown/_scene_mission_mamba.entity",
    "assembly:/_pro/scenes/missions/marrakesh/_scene_spider.entity",
    "assembly:/_pro/scenes/missions/marrakesh/_scene_python.entity",
    "assembly:/_pro/scenes/missions/bangkok/_scene_tiger.entity",
    "assembly:/_pro/scenes/missions/colorado_2/_scene_mission_bull.entity",
    "assembly:/_pro/scenes/missions/hokkaido/_scene_mission_snowcrane.entity",
    "assembly:/_pro/scenes/missions/sheep/scene_sheep.entity",
    "assembly:/_pro/scenes/missions/miami/scene_flamingo.entity",
    "assembly:/_pro/scenes/missions/colombia/scene_hippo.entity",
    "assembly:/_pro/scenes/missions/mumbai/scene_mongoose.entity",
    "assembly:/_pro/scenes/missions/skunk/scene_skunk.entity",
    "assembly:/_pro/scenes/missions/theark/scene_magpie.entity",
    "assembly:/_pro/scenes/missions/salty/mission_seagull/scene_seagull.entity",
    "assembly:/_pro/scenes/missions/greedy/mission_raccoon/scene_raccoon_basic.entity",
    "assembly:/_pro/scenes/missions/opulent/mission_stingray/scene_stingray_basic.entity",
    "assembly:/_pro/scenes/missions/golden/mission_gecko/scene_gecko_basic.entity",
    "assembly:/_pro/scenes/missions/ancestral/scene_bulldog.entity",
    "assembly:/_pro/scenes/missions/edgy/mission_fox/scene_fox_basic.entity",
    "assembly:/_pro/scenes/missions/wet/scene_rat_basic.entity",
    "assembly:/_pro/scenes/missions/elegant/scene_llama.entity",
    "assembly:/_pro/scenes/missions/trapped/scene_wolverine.entity",
    "assembly:/_pro/scenes/missions/rocky/scene_dugong.entity"
];
